env:
    browser: true
    node: true
    es6: true
    atomtest: true
extends: 'eslint:recommended'
parserOptions:
    sourceType: module
    ecmaVersion: 2017
rules:
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
        -
            allowTemplateLiterals: true
    semi:
        - error
        - always
    no-console:
        - off
    max-len:
        - error
        -
            code: 120
    no-cond-assign:
        - off
